# Generated by Django 3.2.9 on 2023-09-04 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.RenameField(
            model_name='category',
            old_name='first_name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='text',
        ),
        migrations.CreateModel(
            name='Company_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyImage', models.ImageField(upload_to='product/', verbose_name='Image')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company_Image',
                'verbose_name_plural': 'Company_Images',
            },
        ),
    ]
