# Generated by Django 3.2.9 on 2023-09-04 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_company_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Store_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyImage', models.ImageField(upload_to='product/', verbose_name='Image')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Store_Image',
                'verbose_name_plural': 'Store_Images',
            },
        ),
        migrations.RemoveField(
            model_name='company_image',
            name='Company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Company_Image',
        ),
    ]
