# Generated by Django 3.2.9 on 2023-09-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discount_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='valid_for',
            field=models.CharField(choices=[('EG', 'EGYPT'), ('SA', 'SUDIARABIA'), ('JR', 'Junior')], default='EG', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='valid_until',
            field=models.DateTimeField(),
        ),
    ]
