# Generated by Django 3.2.9 on 2023-09-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230905_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extra_text',
            field=models.CharField(blank=True, default='كوبون فعال وموثوق', max_length=30, null=True),
        ),
    ]
