# Generated by Django 3.2.9 on 2023-09-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20230905_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discount_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='extra_text',
            field=models.CharField(blank=True, default='كوبون فعال وموثوق', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='offer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='percentage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_txt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=100),
        ),
    ]
