# Generated by Django 3.2.9 on 2023-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20230908_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AddField(
            model_name='store',
            name='store_img_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
