# Generated by Django 3.2.9 on 2023-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230909_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_img_url',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
