# Generated by Django 3.2.9 on 2023-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_post_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
