# Generated by Django 3.2.9 on 2023-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_store_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='post',
            name='last_modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='store',
            name='last_modified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
