# Generated by Django 3.2.9 on 2023-10-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_store_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_img_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
