# Generated by Django 3.2.9 on 2023-10-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_store_store_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
