# Generated by Django 3.2.9 on 2023-10-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_store_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='text',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
