# Generated by Django 3.2.9 on 2023-10-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20231002_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='last_modified_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
