# Generated by Django 3.2.9 on 2023-10-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_store_last_modified_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='store.Category'),
        ),
    ]
