# Generated by Django 3.2.9 on 2023-10-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_store_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_image',
            name='image',
            field=models.ImageField(null=True, upload_to='stores_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='store_image',
            name='img_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
