# Generated by Django 3.2.9 on 2023-10-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20231004_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_image',
            name='img_url',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
