# Generated by Django 3.2.9 on 2023-10-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_store_image_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_image',
            name='img_url',
            field=models.CharField(default='', max_length=100, null=True, unique=True),
        ),
    ]
