# Generated by Django 3.2.9 on 2023-10-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_store_image_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_image',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True, unique=True),
        ),
    ]
